#!/usr/bin/env bash
#
# install.sh — build a Release PomodoroFocus and install it to /Applications.
#
# The app you launch day-to-day is a build artifact, not source. Because the
# Xcode project is generated by XcodeGen and the .app is gitignored, a `git pull`
# or a source rebuild does NOT update your installed copy — you must rebuild and
# re-copy it, or you'll keep launching a stale binary missing recent features.
# This script does that in one step.
#
# Usage:  ./install.sh
#
set -euo pipefail

cd "$(dirname "$0")"

DEST="/Applications/Pomodoro Focus.app"   # installed name (CFBundleDisplayName)

echo "▸ Generating Xcode project from project.yml…"
xcodegen generate

echo "▸ Building Release…"
xcodebuild -scheme PomodoroFocus -configuration Release \
  -destination 'platform=macOS' build CODE_SIGNING_ALLOWED=NO >/dev/null

# Resolve the built product directory (robust against DerivedData hashing / worktrees).
BUILT_DIR=$(xcodebuild -scheme PomodoroFocus -configuration Release -showBuildSettings 2>/dev/null \
  | awk -F' = ' '/ BUILT_PRODUCTS_DIR =/ {gsub(/^[[:space:]]+/, "", $2); print $2; exit}')
BUILT_APP="$BUILT_DIR/PomodoroFocus.app"

if [ ! -d "$BUILT_APP" ]; then
  echo "✗ Could not locate the built app at: $BUILT_APP" >&2
  exit 1
fi

echo "▸ Quitting any running instance…"
osascript -e 'quit app "Pomodoro Focus"' 2>/dev/null || true
pkill -x PomodoroFocus 2>/dev/null || true

echo "▸ Installing to: $DEST"
rm -rf "$DEST"
cp -R "$BUILT_APP" "$DEST"

echo "✓ Installed build $(stat -f '%Sm' -t '%Y-%m-%d %H:%M' "$DEST/Contents/MacOS/PomodoroFocus")."
echo "  Launch it from /Applications or Spotlight (it lives in the menu bar — no Dock icon)."
